<a href="https://colab.research.google.com/github/rehmanaly0051/Pytorch-IN-DeepLearning/blob/main/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


# ***Intro to Tensors***

In [2]:
# Scalar
scalar = torch.tensor(10)
scalar

tensor(10)

In [3]:
#scalar.ndim Checking the dimension.
scalar.item()  # Getting back a python int

10

In [4]:
# Vectors .. Magnitude and Direction ..
vector = torch.tensor([7,7])
vector
# vector.ndim

tensor([7, 7])

In [5]:
vector.shape

torch.Size([2])

In [6]:
MATRIX = torch.tensor([[1,1],[2,2],[3,3],[4,4]])
MATRIX
# MATRIX.ndim

tensor([[1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

In [7]:
TENSOR = torch.tensor([[[1, 2, 3],[4, 5, 6], [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [8]:
TENSOR.shape

torch.Size([1, 3, 3])

In [9]:
TENSOR.ndim

3

## Random Tensors
### why random tensors
 Because many nn start with tensors full of random numbers adjust those random numbers to better represent the data.

In [10]:
random_tensor = torch.rand(3,3,14)
random_tensor

tensor([[[5.8034e-01, 3.4850e-01, 3.6258e-01, 9.0870e-01, 6.6868e-01,
          2.2082e-01, 9.8476e-01, 6.1284e-02, 3.2065e-01, 7.6009e-01,
          2.6305e-01, 6.8288e-01, 1.4290e-01, 1.0535e-01],
         [6.6575e-03, 3.5895e-01, 8.4522e-01, 4.8809e-01, 8.6837e-01,
          1.5719e-03, 3.4501e-01, 4.1285e-01, 1.8926e-01, 2.5852e-01,
          7.8620e-01, 4.5751e-01, 5.4187e-01, 7.7046e-01],
         [8.4646e-01, 9.0495e-01, 8.1476e-01, 7.0870e-01, 2.4704e-01,
          7.2448e-02, 3.3028e-01, 1.4167e-02, 4.9049e-01, 9.9179e-01,
          8.7657e-01, 9.9308e-01, 6.9850e-02, 1.5106e-02]],

        [[8.7363e-01, 9.8927e-01, 2.5882e-01, 6.4120e-02, 3.5242e-01,
          4.4295e-01, 2.4584e-01, 2.8151e-01, 8.8799e-02, 7.1616e-02,
          5.1598e-01, 5.5950e-01, 8.1181e-01, 9.9365e-01],
         [6.3478e-01, 5.8582e-01, 9.6140e-01, 1.9397e-01, 1.1050e-01,
          5.9073e-01, 3.0473e-01, 2.7847e-01, 2.9110e-01, 2.9869e-01,
          6.4056e-01, 7.3356e-01, 1.8725e-01, 8.6826e-01],
   

In [11]:
random_tensor.ndim

3

In [12]:
# Creating a random tensor with similar to an image tensor
random_size_image_tensr = torch.rand(size=(3, 224,224)) # height, width, color chanals (RGB)
random_size_image_tensr.shape, random_size_image_tensr.ndim

(torch.Size([3, 224, 224]), 3)

## Zeros and Ones




In [13]:
zeros = torch.zeros(size=(3,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [14]:
ones = torch.ones(size=(3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [15]:
random_tensor.dtype, ones.dtype, zeros.dtype

(torch.float32, torch.float32, torch.float32)

## Creating a range of tensors and tensor-like

In [16]:
# creating  tensor range
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
# creating tensor like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [18]:
# creating tensor datatypes
# single precision is 32 but and half precision is 16 bit
float_32_tensor  = torch.tensor([3.0,6.0,9.0],
                                dtype = None, # What datatype is the tensor(e.g float 32 or float16)
                                device = None, # what device is your tensor on
                                requires_grad=False) # weather or not track gradients with this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [19]:
float_32_tensor.dtype

torch.float32

In [20]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [21]:
float_16_tensor * float_32_tensor # 3^2, 6^2, 9^2

tensor([ 9., 36., 81.])

In [22]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [23]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

## Getting Infor From Tensor (Tensor Attributes)

###tensor not on right dtype, tensor.dtype
###tensor not right shape, tensor.shape
###tensor not on right device, tensor.device

> Add blockquote



In [24]:
# creating a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.1344, 0.3102, 0.9055, 0.1120],
        [0.1274, 0.3754, 0.4721, 0.7573],
        [0.3650, 0.2728, 0.9230, 0.2014]])

In [25]:
# Finding out detail about tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.1344, 0.3102, 0.9055, 0.1120],
        [0.1274, 0.3754, 0.4721, 0.7573],
        [0.3650, 0.2728, 0.9230, 0.2014]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


## Minuplating Tensor (tensor Operations)

### Addition
### Subtraction
### Multiplication (Element wise)
### Division
### Matrix Multiplication


In [26]:
# creating a tensor and add 10 on it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [27]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [28]:
# Substraction by 10
tensor - 10

tensor([-9, -8, -7])

In [29]:
# pytorch in-built  functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [30]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [31]:
torch.sub(tensor, 10)

tensor([-9, -8, -7])

In [32]:
torch.div(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

## MAtrix multiplication
### 2 ways
### element wise mul.
### Matrix mul.


In [33]:
# ELement Wise Multipliacation
print(tensor, '*', tensor)
print(f'Equals: {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [34]:
# Matrix Multiplication
print(tensor, '*', tensor)
print(f'Equals: {tensor.matmul(tensor)}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: 14


In [35]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.44 ms, sys: 70 µs, total: 1.51 ms
Wall time: 1.88 ms


In [36]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 261 µs, sys: 0 ns, total: 261 µs
Wall time: 197 µs


tensor(14)

In [37]:
tensor_A = torch.tensor([[1,2,3], [4, 5, 6]])
tensor_A

tensor([[1, 2, 3],
        [4, 5, 6]])

In [38]:
tensor_B = torch.tensor([[3, 2, 1],[6, 5, 4]])
tensor_B

tensor([[3, 2, 1],
        [6, 5, 4]])

In [39]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[10, 28],
        [28, 73]])

## Finding min, max, mean, sum etc..

In [40]:
x = torch.range(1, 100, 10)
x

<ipython-input-40-b34a38d6b3ad>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  x = torch.range(1, 100, 10)


tensor([ 1., 11., 21., 31., 41., 51., 61., 71., 81., 91.])

In [41]:
torch.min(x)

tensor(1.)

In [42]:
torch.max(x)

tensor(91.)

In [43]:
# mean() require float32 datatype
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [44]:
torch.sum(x), x.sum()

(tensor(460.), tensor(460.))

## Finding positional min, max (index)

In [45]:
x.argmin(), x[0]

(tensor(0), tensor(1.))

In [46]:
x.argmax(), x[9]

(tensor(9), tensor(91.))

## Reshaping, stacking, squeezing, unsqueezing tensor

In [47]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [48]:
# reshapping
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [49]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [50]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [51]:
# stacking (vstack use dim=0, hstack use dim=1)
x_stacked = torch.stack([x, x, x, x], dim=0) # dim=1
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [52]:
# squeezing (removing extra dimension from tensor)
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [53]:
x_squeze = x_reshaped.squeeze() # x_reshaped.squeeze().shape
x_squeze, x_squeze.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [54]:
# Unsqeesing adding an extra dimension
x_squeze.unsqueeze(dim=0), x_squeze.unsqueeze(dim=0).shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [55]:
# torch.prmute changing the values
x_original = torch.rand(size = (224, 224, 3)) # height,width,color channels(rgb)
x_original.shape, x_original.ndim, x_original.permute(2, 0, 1).shape

(torch.Size([224, 224, 3]), 3, torch.Size([3, 224, 224]))

In [56]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [57]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [58]:
x[0][1]

tensor([4, 5, 6])

In [59]:
x[0][1][1] # middle value form the tensor.

tensor(5)

In [60]:
x[:,1], x[0][1]

(tensor([[4, 5, 6]]), tensor([4, 5, 6]))

In [61]:
x[:,:,1], x[:,2,1]  # all dimensions, all rows but first column

(tensor([[2, 5, 8]]), tensor([8]))

In [62]:
x[0,0,:]

tensor([1, 2, 3])

## Pytorch and Numpy

### data in numpy want in tensor, `torch.from_numpy(ndarray)`
### pytrch to numpy `torch.Tensor.numpy()`

In [63]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [64]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float32)

In [65]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [66]:
array = array + 1
tensor , array

(tensor([1., 2., 3., 4., 5., 6., 7.]), array([2., 3., 4., 5., 6., 7., 8.]))

In [67]:
tensor = torch.ones(10)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [68]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproduciility (random out of random)

In [69]:
torch.rand(3,3)

tensor([[0.7618, 0.3984, 0.4345],
        [0.5751, 0.2253, 0.9830],
        [0.6784, 0.2998, 0.4229]])

In [70]:
import torch

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8902, 0.5098, 0.8837, 0.7612],
        [0.8595, 0.5130, 0.7259, 0.6386],
        [0.2433, 0.6803, 0.6613, 0.6210]])
tensor([[0.9388, 0.2856, 0.0603, 0.7528],
        [0.0290, 0.1653, 0.6828, 0.7655],
        [0.7316, 0.4038, 0.7416, 0.1535]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [71]:
import torch

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED) # works for only block of code
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED) # works for only block of code
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Accessing GPU

In [2]:
!nvidia-smi

Tue Mar 18 10:44:29 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   38C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

## Check for GPU access with pytorch

In [3]:
# check for gpu access for pytorch
import torch
torch.cuda.is_available()

True

In [4]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
# count number of devices
torch.cuda.device_count()

1