<a href="https://colab.research.google.com/github/rehmanaly0051/Pytorch-IN-DeepLearning/blob/main/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


# ***Intro to Tensors***

In [2]:
# Scalar
scalar = torch.tensor(10)
scalar

tensor(10)

In [3]:
#scalar.ndim Checking the dimension.
scalar.item()  # Getting back a python int

10

In [4]:
# Vectors .. Magnitude and Direction ..
vector = torch.tensor([7,7])
vector
# vector.ndim

tensor([7, 7])

In [5]:
vector.shape

torch.Size([2])

In [6]:
MATRIX = torch.tensor([[1,1],[2,2],[3,3],[4,4]])
MATRIX
# MATRIX.ndim

tensor([[1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

In [7]:
TENSOR = torch.tensor([[[1, 2, 3],[4, 5, 6], [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [8]:
TENSOR.shape

torch.Size([1, 3, 3])

In [9]:
TENSOR.ndim

3

## Random Tensors
### why random tensors
 Because many nn start with tensors full of random numbers adjust those random numbers to better represent the data.

In [10]:
random_tensor = torch.rand(3,3,14)
random_tensor

tensor([[[2.1047e-01, 2.5717e-01, 9.6843e-01, 6.2748e-01, 9.9216e-01,
          3.5487e-01, 8.2435e-01, 2.6346e-01, 2.9661e-02, 8.8964e-01,
          5.0267e-01, 9.1084e-01, 7.2096e-01, 3.2245e-01],
         [8.5639e-01, 3.4541e-01, 3.5827e-01, 1.2600e-01, 3.1478e-01,
          7.5746e-01, 2.2381e-01, 8.0959e-01, 6.4897e-01, 6.2019e-01,
          6.5683e-01, 4.3778e-01, 7.5816e-01, 6.5490e-01],
         [1.7183e-01, 3.2983e-01, 1.1182e-01, 9.6425e-01, 7.2647e-01,
          6.0365e-02, 6.3584e-01, 8.9617e-01, 2.2705e-01, 5.4589e-01,
          6.7720e-02, 3.8098e-01, 9.8127e-01, 1.8286e-01]],

        [[3.6154e-01, 3.4863e-01, 6.9140e-01, 5.1383e-01, 5.3451e-01,
          8.9560e-01, 9.8724e-01, 8.8980e-01, 2.8586e-01, 5.4001e-01,
          5.3210e-01, 1.0171e-01, 6.1106e-02, 3.6524e-01],
         [9.5092e-01, 5.0448e-02, 7.3739e-01, 6.7992e-01, 7.3706e-01,
          3.4900e-02, 6.1719e-01, 2.6228e-02, 7.1801e-01, 2.2613e-01,
          3.2536e-01, 2.9312e-01, 6.4213e-01, 2.3117e-01],
   

In [11]:
random_tensor.ndim

3

In [12]:
# Creating a random tensor with similar to an image tensor
random_size_image_tensr = torch.rand(size=(3, 224,224)) # height, width, color chanals (RGB)
random_size_image_tensr.shape, random_size_image_tensr.ndim

(torch.Size([3, 224, 224]), 3)

## Zeros and Ones




In [24]:
zeros = torch.zeros(size=(3,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [14]:
ones = torch.ones(size=(3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [15]:
random_tensor.dtype, ones.dtype, zeros.dtype

(torch.float32, torch.float32, torch.float32)

## Creating a range of tensors and tensor-like

In [16]:
# creating  tensor range
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
# creating tensor like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [18]:
# creating tensor datatypes
# single precision is 32 but and half precision is 16 bit
float_32_tensor  = torch.tensor([3.0,6.0,9.0],
                                dtype = None, # What datatype is the tensor(e.g float 32 or float16)
                                device = None, # what device is your tensor on
                                requires_grad=False) # weather or not track gradients with this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [19]:
float_32_tensor.dtype

torch.float32

In [20]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [21]:
float_16_tensor * float_32_tensor # 3^2, 6^2, 9^2

tensor([ 9., 36., 81.])

In [28]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [29]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

## Getting Infor From Tensor (Tensor Attributes)

###tensor not on right dtype, tensor.dtype
###tensor not right shape, tensor.shape
###tensor not on right device, tensor.device

> Add blockquote



In [35]:
# creating a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0022, 0.5220, 0.0710, 0.1163],
        [0.5598, 0.1958, 0.3581, 0.5367],
        [0.3615, 0.2099, 0.9465, 0.1192]])

In [36]:
# Finding out detail about tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.0022, 0.5220, 0.0710, 0.1163],
        [0.5598, 0.1958, 0.3581, 0.5367],
        [0.3615, 0.2099, 0.9465, 0.1192]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


## Minuplating Tensor (tensor Operations)

### Addition
### Subtraction
### Multiplication (Element wise)
### Division
### Matrix Multiplication


In [46]:
# creating a tensor and add 10 on it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [47]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [48]:
# Substraction by 10
tensor - 10

tensor([-9, -8, -7])

In [49]:
# pytorch in-built  functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [50]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [51]:
torch.sub(tensor, 10)

tensor([-9, -8, -7])

In [52]:
torch.div(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

## MAtrix multiplication
### 2 ways
### element wise mul.
### Matrix mul.


In [54]:
# ELement Wise Multipliacation
print(tensor, '*', tensor)
print(f'Equals: {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])
